name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - dockerfile: 'agent/docker/jvm/Dockerfile'
            tag: 'jvm'
#          - dockerfile: 'agent/docker/jvm/Dockerfile.alpine'
#            tag: 'jvm-alpine'
#          - dockerfile: 'agent/docker/bpf/Dockerfile'
#            tag: 'bpf'
#          - dockerfile: 'agent/docker/python/Dockerfile'
#            tag: 'python'
#          - dockerfile: 'agent/docker/ruby/Dockerfile'
#            tag: 'ruby'
          - dockerfile: 'agent/docker/perf/Dockerfile'
            tag: 'perf'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set env
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build Docker Image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        file: ${{ matrix.image.dockerfile }}
        tags: sumologic/kubectl-flame:${{ steps.vars.outputs.tag }}-${{ matrix.image.tag }}

  build-go:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.38
