name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set env
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build JVM Docker Image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        file: 'agent/docker/jvm/Dockerfile'
        tags: sumologic/kubectl-flame:${{ steps.vars.outputs.tag }}-jvm
    - name: Build JVM Alpine Docker Image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        file: 'agent/docker/jvm/Dockerfile.alpine'
        tags: sumologic/kubectl-flame:${{ steps.vars.outputs.tag }}-jvm-alpine
    - name: Build BPF Docker Image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        file: 'agent/docker/bpf/Dockerfile'
        tags: sumologic/kubectl-flame:${{ steps.vars.outputs.tag }}-bpf
    - name: Build Python Docker Image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        file: 'agent/docker/python/Dockerfile'
        tags: sumologic/kubectl-flame:${{ steps.vars.outputs.tag }}-python
    - name: Build Ruby Docker Image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        file: 'agent/docker/ruby/Dockerfile'
        tags: sumologic/kubectl-flame:${{ steps.vars.outputs.tag }}-ruby
    - name: Build perf Docker Image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        file: 'agent/docker/perf/Dockerfile'
        tags: sumologic/kubectl-flame:${{ steps.vars.outputs.tag }}-perf
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.38
